title: "Wandering Blog"
author: "Default Author"
description: "Some short description of your blog can go here."
theme: "minima"

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other  

